apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-nonprivileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true